[package]
name = "md-wasm"
version = "0.1.0"
authors = ["MSvbd"]
description = "MD simulation functions."
license = "MIT/Apache-2.0"
repository = ""
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"